export default function DisclaimerSection() {
  return (
    <section className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pb-14">
      <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-xl px-5 py-4 text-xs text-amber-800 dark:text-amber-200 leading-relaxed">
        <strong>Disclaimer:</strong> Invoices generated by BuildWithRiz are for informational and
        business documentation purposes. They do not constitute legal, tax, or financial advice.
        Please consult a qualified accountant or legal professional for compliance with your local
        invoicing and taxation regulations.
      </div>
    </section>
  );
}
